services:
  dxhx-coop-server:
    image: git.sbotnas.io/kevin/dxhx-coop-server:latest
    container_name: dxhx-coop-server
    environment:
      - "TZ=America/New_York"
      - "PUID=1000" # Optional: Set the UID for the user inside the container; Default: 1000
      - "PGID=1000" # Optional: Set the GID for the user inside the container; Default: 1000
      - "SERVER_NAME=Another Docker HX Coop Server" # Required: Name of your server; Default: Another Docker HX Coop Server
      - "SERVER_PASSWORD=" # Optional: Server password. Clients will need DXMTL to enable a GUI password field, enter in console: open <youripaddress>:<port>?password=<password> in order to connect; Default: unset
      - "SERVER_PORT=" # Optional: Port the Server will listen on; Default: 7990
      - "SERVER_INI=" # Optional: Specify a custom server configuration file (with file extension). File must be in Deus Ex System/ folder; Default: unset
      - "ADMIN_PASSWORD=" # Optional: Admin password (if empty admin login will be disabled); Default: unset
      - "MAP=00_Training" # Requird: Map to play; Default: 00_Training
      - "MUTATORS=" # Optional: A comma-separated list of Mutators to load; Default: unset
      - "MAX_PLAYERS=8" # Optional, Max Players for the server; Default: 8
      - "DIFFICULTY=1" # Required: Specify game difficulty, 0 = Easy, 1 = Medium, 2 = Hard, or 3 = DeusEx (Realistic); Default: 1 (Medium)
      - "ADDITIONAL_ARGS=" # Optional: Pass additional arguments such as multihome or specify a custom log file; Default: unset
      - "DX_RANDOMIZER=False" # Optional: Enable DX Randomizer mod (will also download mod if not available in game folder); Default: False
      - "DX_DEATHMARKERS=True" # Optional: Death Markers show you where other players have died, using a skull icon. It also tells you how they died and when (only for DX Randomizer); Default: True
      - "DX_ENABLE_TELEMETRY=False" # Optional: Enable Online Features for DX Randomizer, including posting in-game events to their Mastodon bot, updating their death marker database, and leaderboards; Default: False
      - "DX_GAMEMODE=0" # Optional: Gamemode for DX Randomizer (0 = Normal, 1 = Randomizer Lite, 2 = Zero Rando, 3 = Serious Sam Mode, 4 = Speedrun Mode, 5 = WaltonWare); Default: 0 (Normal)
      - "DX_LOADOUT=0" # Optional: Choose the load for DX Randomizer (0 = All Items Allowed, 1 = Prod Plus, 2 = Prod Pure, 3 = Ninja JC, 4 = By the Book, 5 = No Overpowered Weapons, 6 = Don't Give me the GEP Gun, 7 = No Pistols, 8 = No Swords, 9 = Grenades Only, 10 = Freeman Mode; Default = 0 (All Items Allowed)
      - "DX_AUTOUPDATE=True" # Optional: Grab latest version of DX Randomizer on each container boot. See disclaimers in README.md; Default: True
    volumes:
      - /path/to/your/gamefiles:/container/deusex
      - dxhx-coop-wine:/container/.wine
    ports:
      - 7990-7992:7990-7992/udp
    restart: unless-stopped

volumes:
  dxhx-coop-wine:
    name: dxhx-coop-wine
