#!/command/with-contenv sh

GAMEDIR=/container/deusex
hxfiles="exe dll u int" 
umask $UMASK

if [[ "${INSTALL_HX:=False}" = [Tt]rue ]]; then
	for i in $hxfiles; do
	        while [[ ! -e "$GAMEDIR/System/HX.$i" ]]; do
	                echo "HX.$i not found, installing HX"
			cp -r /container/ServerFiles/HX/* $GAMEDIR/
		done
	done

	if [[ ! -e "$GAMEDIR/System/HX.ini" ]]; then
		cp /container/ServerFiles/HX.ini $GAMEDIR/System
	fi

	chown -R wine:wine $GAMEDIR
else
	echo "Skipping HX install"
	exit 0
fi

echo "All HX files found, continuing"
rm -rf /container/ServerFiles/
